# Generated by Django 3.1.6 on 2021-02-12 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210212_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
